# Generated by Django 4.1.5 on 2023-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal_app', '0004_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('SP', 'Cпорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('SO', 'Общество'), ('TE', 'Технологии')], max_length=2, unique=True),
        ),
    ]
